name: NonePowers
version: 1.0.0
main: me.none.powers.NonePowers
api-version: 1.12
author: none
description: 300 powers for none

commands:
  none:
    description: Opens None's power menu
    usage: /none
