name: NonePowers
version: 1.0
main: me.none.powers.NonePowers
api-version: 1.12
author: None
description: None's 300 Powers plugin

commands:
  nonepowers:
    description: Open None's 300 Powers menu
    usage: /nonepowers
